spring:
  application:
    name: registrationlapon
  config:
    import: "optional:configserver:http://config-server:8888"
#  cloud:
#    config:
#      enabled: false

  datasource:
    url: jdbc:postgresql://postgres_15:5432/registration_data_base
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret:
    key: c2VjcmV0X2tleV9mb3Jfand0X2FwcGxpY2F0aW9uX2V4YW1wbGU=
  token:
    time: 60000

logging:
  level:
    org:
      springframework:
        security: DEBUG
    io:
      jsonwebtoken: DEBUG

#eureka:
#  client:
#    enabled: false
#    register-with-eureka: false
#    fetch-registry: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  webjars:
    prefix: /webjars